import type { AppState, Movie } from "./types";

export const movies: Movie[] = [
  {
    id: 693134,
    title: "Dune: Part Two",
    year: 2024,
    runtime: 167,
    director: "Denis Villeneuve",
    genres: ["Science Fiction", "Adventure"],
    poster: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/uhUO7vQQKvCTfQWubOt5MAKokbL.jpg",
    overview: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    palette: { dominant: "#9b593b", secondary: "#34201b", accent: "#d99863" },
  },
  {
    id: 545611,
    title: "Everything Everywhere All at Once",
    year: 2022,
    runtime: 140,
    director: "Daniel Kwan & Daniel Scheinert",
    genres: ["Action", "Adventure", "Science Fiction"],
    poster: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xw383myGoydmJyL2yzFj0tVljll.jpg",
    overview: "An exhausted laundromat owner is swept into a multiversal adventure where she alone can save existence by connecting with lives she could have led.",
    palette: { dominant: "#613276", secondary: "#201127", accent: "#de5db1" },
  },
  {
    id: 569094,
    title: "Spider-Man: Across the Spider-Verse",
    year: 2023,
    runtime: 140,
    director: "Joaquim Dos Santos, Kemp Powers & Justin K. Thompson",
    genres: ["Animation", "Action", "Adventure"],
    poster: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/2I5eBh98Q4aPq8WdQrHdTC8ARhY.jpg",
    overview: "Miles Morales catapults across the Multiverse and encounters a team of Spider-People charged with protecting its very existence.",
    palette: { dominant: "#9d315f", secondary: "#251126", accent: "#f18949" },
  },
  {
    id: 120467,
    title: "The Grand Budapest Hotel",
    year: 2014,
    runtime: 100,
    director: "Wes Anderson",
    genres: ["Comedy", "Drama"],
    poster: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xHDynIimfsgj0ZOs0j5ma8v1vmM.jpg",
    overview: "A legendary concierge and his trusted lobby boy become embroiled in the theft of a priceless Renaissance painting.",
    palette: { dominant: "#9a3f65", secondary: "#311323", accent: "#e5a6b6" },
  },
  {
    id: 496243,
    title: "Parasite",
    year: 2019,
    runtime: 133,
    director: "Bong Joon Ho",
    genres: ["Comedy", "Thriller", "Drama"],
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    overview: "A cash-strapped family slowly insinuates itself into the home of a wealthy household—with unexpected consequences.",
    palette: { dominant: "#516b58", secondary: "#18221b", accent: "#a6b58d" },
  },
  {
    id: 76341,
    title: "Mad Max: Fury Road",
    year: 2015,
    runtime: 120,
    director: "George Miller",
    genres: ["Action", "Adventure", "Science Fiction"],
    poster: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8yACFuo4OaIiKr9hHFlmPcGalKx.jpg",
    overview: "In a ruined wasteland, Max joins Furiosa and a band of rebels fleeing a tyrant in a roaring War Rig.",
    palette: { dominant: "#a84e24", secondary: "#2f1710", accent: "#efa14b" },
  },
  {
    id: 376867,
    title: "Moonlight",
    year: 2016,
    runtime: 111,
    director: "Barry Jenkins",
    genres: ["Drama"],
    poster: "https://image.tmdb.org/t/p/w500/6Eg6OfwghmSLVtt2sfGD5YOEFjI.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/v0qkC1c06zg2XsBmOb1S90JNiLg.jpg",
    overview: "A young man grapples with identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and adulthood.",
    palette: { dominant: "#24517b", secondary: "#151938", accent: "#b6568d" },
  },
  {
    id: 531428,
    title: "Portrait of a Lady on Fire",
    year: 2019,
    runtime: 121,
    director: "Céline Sciamma",
    genres: ["Drama", "Romance"],
    poster: "https://image.tmdb.org/t/p/w500/lH2hSK6F1FZmS3ao384kZCMsbCl.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/foFq1RZWQIgFuCQ0nyYccywjFyX.jpg",
    overview: "On an isolated island, an artist is commissioned to paint a wedding portrait without her subject knowing.",
    palette: { dominant: "#8c4c2c", secondary: "#281610", accent: "#d89a5d" },
  },
  {
    id: 419430,
    title: "Get Out",
    year: 2017,
    runtime: 104,
    director: "Jordan Peele",
    genres: ["Mystery", "Thriller", "Horror"],
    poster: "https://image.tmdb.org/t/p/w500/mE24wUCfjK8AoBBjaMjho7Rczr7.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/o8dPH0ZSIyyViP6rjRX1djwCUwI.jpg",
    overview: "A young Black man visits his girlfriend's family estate and uncovers something far more sinister than awkward hospitality.",
    palette: { dominant: "#46596d", secondary: "#141d25", accent: "#93a8bc" },
  },
  {
    id: 129,
    title: "Spirited Away",
    year: 2001,
    runtime: 125,
    director: "Hayao Miyazaki",
    genres: ["Animation", "Family", "Fantasy"],
    poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg",
    overview: "A ten-year-old enters a world ruled by gods, witches, and spirits where humans are changed into beasts.",
    palette: { dominant: "#527b77", secondary: "#172827", accent: "#d3786d" },
  },
];

export const initialState: AppState = {
  diary: [],
  reviews: [],
  ranked: [],
  watchlist: [],
  movieCache: [...movies],
  comparisons: [],
  rankHistory: [],
  activeRankingSession: null,
  activeRankingEntryId: null,
  activeRankingOriginalRank: null,
  activeRankingOriginalVerdict: null,
  activeRankingLastActivityAt: null,
  activeRankingSessionId: null,
  activeRankingRevision: 0,
  activeRankingReason: null,
  activeRankingStatus: null,
  committedRankingSessionIds: [],
};

export function movieById(id: number): Movie {
  return movies.find((movie) => movie.id === id) ?? {
    id,
    title: "Untitled film",
    year: new Date().getFullYear(),
    runtime: null,
    director: "Unknown director",
    genres: [],
    poster: null,
    backdrop: null,
    overview: "",
    palette: { dominant: "#3d345d", secondary: "#17152b", accent: "#8f83d9" },
  };
}

export function cacheMovies(incoming: Movie[]): void {
  incoming.forEach((movie) => {
    const index = movies.findIndex((existing) => existing.id === movie.id);
    if (index >= 0) movies[index] = movie;
    else movies.push(movie);
  });
}
